<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Dental.Framework.Storage</RootNamespace>
    <AssemblyName>Dental.Framework.Storage</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1062;CA1848;CA1031;CA2007;CA1873;CA1812;CA1054;CA1055;CA1056;CA1308</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Dental.Framework.Core.csproj" />
    <ProjectReference Include="..\Shared\Dental.Framework.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

</Project>
