<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Dental.Framework.Eventing</RootNamespace>
    <AssemblyName>Dental.Framework.Eventing</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1062;CA1848;CA1031;CA2007;CA1812;CA1034;CA2000;CA1873</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Dental.Framework.Core.csproj" />
    <ProjectReference Include="..\Eventing.Abstractions\Dental.Framework.Eventing.Abstractions.csproj" />
    <ProjectReference Include="..\Persistence\Dental.Framework.Persistence.csproj" />
    <ProjectReference Include="..\Shared\Dental.Framework.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>

</Project>
