<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Dental.Framework.Jobs</RootNamespace>
    <AssemblyName>Dental.Framework.Jobs</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1062;CA1848;CA1031;CA2007;CA1873;CA1812</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Dental.Framework.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
  </ItemGroup>

</Project>
