<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Dental.Modules.Auditing.Contracts</RootNamespace>
    <AssemblyName>Dental.Modules.Auditing.Contracts</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1034;CA1724;CA2227</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Eventing.Abstractions\Dental.Framework.Eventing.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Shared\Dental.Framework.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.Abstractions" />
  </ItemGroup>

</Project>
